### PR TITLE
PKCE support for rails 3.2

### PR DESCRIPTION
**Pull request by n-anil**
Backport PCKE support related changes from Doorkeeper version v 5.5.1.

### CODE REVIEW

**Review by elliterate — COMMENTED** [review]
I see this error when running the test suite:

```
  1) Authorization Code Flow with PKCE s256 mobile app requests an access token with authorization code and without secret
     Failure/Error: expect(JSON.parse(page.driver.response.body).fetch(key)).to eq(value)

     KeyError:
       key not found: "error"
     # ./spec/support/helpers/request_spec_helper.rb:59:in `fetch'
     # ./spec/support/helpers/request_spec_helper.rb:59:in `driver_should_have_json'
     # ./spec/requests/flows/authorization_code_spec.rb:182:in `block (4 levels) in <top (required)>'
```

**Comment by n-anil** [comment]
@elliterate This commit https://github.com/vhx/doorkeeper/pull/1/commits/da6ff09e93d5fbe1e6056cbbd1cdd1934d498d02 broke one of the test case. Fixed the issue.

**Comment by elliterate** [comment]
@n-anil Did you cherry-pick specific commits? If so, do you have a list of them?

**Comment by n-anil** [comment]
@elliterate I tried that and there were lot of unwanted change-set coming belonging to other versions of doorkeeper hence went with the hard way of going through each PR's related to PKCE and manually adding the changes.

I discarded the change-set mid-way and i don't have the list of commits right now.

**Review by elliterate — APPROVED** [review]

**Pull request merged**
